#!/usr/bin/env python

import os
import sys
import click
import sh

git = sh.git


class BadHash (click.ClickException):
    pass


@click.command()
@click.argument('hash')
def blob_created_at(hash):
    try:
        git('rev-parse', '--verify', hash)
    except sh.ErrorReturnCode as err:
        raise BadHash('invalid content hash: %s' % hash)


if __name__ == '__main__':
    blob_created_at()
